#!/usr/bin/env bash

#   -------------------------------------------------------------
#   Cap PipeWire/PulseAudio default sink volume
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Wynter
#   Description:    Pull the default sink back to 80% if it
#                   crosses that threshold.
#   License:        BSD-2-Clause
#   Source file:    roles/core/drivers/files/pulseaudio/cap-volume/cap-volume.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by Wynter SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>
#   -------------------------------------------------------------

MAX_VOL=80

limit_volume() {
    # Get the current volume percentage of the default sink
    local current_vol
    current_vol=$(pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null | grep -oP '\d+%' | head -1 | tr -d '%')

    # If the volume is greater than our cap, force it back down
    if [[ -n "$current_vol" && "$current_vol" -gt "$MAX_VOL" ]]; then
        pactl set-sink-volume @DEFAULT_SINK@ "${MAX_VOL}%"
    fi
}

# Check immediately on startup in case it's already too loud
limit_volume

# Listen to PipeWire/Pulse events and trigger the check on any sink change
pactl subscribe | grep --line-buffered "sink" | while read -r _; do
    limit_volume
done
