#!/usr/bin/env python3
#   -------------------------------------------------------------
#   Chrome monthly history
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   Description:    Extract from the Chrome history SQLite database
#                   the history of the specified or current month
#   Filters:        A lot of URLs are excluded, as we're interested
#                   in the URLs that we can blog about
#   License:        BSD-2-Clause
#   Source file:    roles/workstation/userland-software/files/scripts/chrome-monthly-history.py
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by Wynter SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>
#   -------------------------------------------------------------


from datetime import date
from pathlib import Path
import re
import shutil
import sqlite3
import sys
from typing import List


#   -------------------------------------------------------------
#   Database path
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


CANDIDATES_HISTORY_DB = [
    Path.home() / ".config/google-chrome-unstable/Default/History",
    Path.home() / ".config/google-chrome/Default/History",
]


def find_history_db() -> Path|None:
    for candidate in CANDIDATES_HISTORY_DB:
        if candidate.exists():
            return candidate

    return None


#   -------------------------------------------------------------
#   Database queries
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


def extract_monthly_urls(db_path, month) -> List[str]:
    tmpfile = db_path.with_suffix(".tmp")
    shutil.copyfile(db_path, tmpfile)

    conn = sqlite3.connect(str(tmpfile))
    cursor = conn.cursor()

    # Why 11644473600? See https://stackoverflow.com/q/76855251/1930997
    query = f"""
SELECT
    DATE(last_visit_time/1000000-11644473600,'unixepoch') as visit_date,
    url, title
FROM urls
WHERE
    hidden=0
    AND visit_date BETWEEN '{month}-01' AND '{month}-31'
    AND url NOT LIKE '%pinterest.com%'
    AND url NOT LIKE '%google.com%'
    AND url NOT LIKE '%dereckson.be%'
    AND url NOT LIKE '%nasqueron.org%'
    AND url NOT LIKE '%youtube.com%'
    AND url NOT LIKE '%leonardo.ai%'
    AND url NOT LIKE '%adobe.com%' -- Firefly, color.adobe.com
ORDER BY visit_date ASC;
"""

    cursor.execute(query)
    urls = cursor.fetchall()

    conn.close()
    tmpfile.unlink()

    return urls


#   -------------------------------------------------------------
#   Calendar helper methods
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


RE_MONTH=r"\d{4}-(0[1-9]|1[0-2])"


def current():
    """
    Return the current month in YYYY-MM format.
    """
    return date.today().strftime("%Y-%m")


def is_valid_month(expression: str) -> bool:
    """
    Validate a month expression in YYYY-MM format.
    Accepts years 0000-9999 and months 01-12.
    """
    return bool(re.fullmatch(RE_MONTH, expression))


#   -------------------------------------------------------------
#   Application entry point
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


def run(month: str):
    db_path = find_history_db()
    if db_path is None:
        print("Can't find Chrome history database", file=sys.stderr)
        sys.exit(2)

    urls = extract_monthly_urls(db_path, month)
    for url in urls:
        print(url)


if __name__ == "__main__":
    argc = len(sys.argv)

    if argc < 2:
        run(current())
        sys.exit(0)

    arg_month = sys.argv[1]

    if not is_valid_month(sys.argv[1]):
        print("Invalid month expression")
        sys.exit(1)

    run(arg_month)
