#!/bin/sh

#   -------------------------------------------------------------
#   Restore Ethernet controller for I226-V
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Wynter
#   Description:    Workaround for Ethernet controller not answering
#                   anymore on Linux systems.
#   License:        BSD-2-Clause
#   Reference:      https://blog.cordx.cx/posts/2024-09-19-intel-net-cont-problem
#   Source file:    roles/workstation/userland-software/files/scripts/restore-ethernet-controller.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by Wynter SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>
#   -------------------------------------------------------------

set -e

#   -------------------------------------------------------------
#   Ensure user is root
#
#   Note: POSIX shells don't always define $UID or $EUID.
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# shellcheck disable=SC3028
if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    echo "This command must be run as root." >&2
    exit 1
fi

#   -------------------------------------------------------------
#   Get PCI information
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

device_id=$(lspci | grep I226-V | awk '{print $1}')

if [ "$device_id" = "" ]; then
    echo "Chipset not found." >&2
    exit 1
fi

device_path=$(find /sys/bus/pci/devices -name "0000:$device_id")

#   -------------------------------------------------------------
#   Fix: remove device and rescan
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo 1 > "$device_path/remove"
echo 1 > /sys/bus/pci/rescan
