server:
  interface: 127.0.0.1
  interface: ::1
  port: 53

  access-control: 127.0.0.0/8 allow
  access-control: ::1 allow

  hide-identity: yes
  hide-version: yes
  harden-below-nxdomain: yes
  harden-referral-path: yes
  qname-minimisation: yes

  do-ip4: yes
  do-ip6: yes

forward-zone:
  name: "lan."
  forward-addr: {{ gateway }}

forward-zone:
  name: "."
  {% for server in dns_servers %}
  forward-addr: {{ server }}
  {% endfor %}
