#   -------------------------------------------------------------
#   Configuration for hash resolver
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

gerrit:
  - https://gerrit.wikimedia.org/r/
